FROM node:current-alpine3.20 AS build-stage
WORKDIR /app
COPY package*.json .
RUN yarn install
COPY . .
RUN yarn run build

FROM nginx:1.27-alpine-slim
RUN addgroup app && adduser -S -G app app
RUN chown -R app:app /var/run/
RUN chown -R app:app /var/cache/nginx
USER app
COPY --from=build-stage /app/build /usr/share/nginx/html/
EXPOSE 80
CMD [ "nginx","-g","daemon off;" ]